### ISSUE TITLE
g_subCount  only goes up

### ISSUE THREAD

**Issue by Devil4ngle** [Devil4ngle/mp.au3#1]
@nomi-san, thanks for directing me to this library. 
There is #define MAX_SUBPOCS 10, and g_subCount only gets counted up. Should it not go back to 0 on MP_WaitAll and MP_Wait, counted down? Or will this create a fatal error?

**Comment by nomi-san** [comment]
You can only create up to 10 procs at once and cant decrease counting when a proc exits.
When reaching the limit, fork() just do nothing and return -1.

This library has some issues, do not use for production.

**Comment by Devil4ngle** [comment]
@nomi-san  so If I would set
```
 EXPORT void MP_WaitAll()
{
    if (g_subCount == 0) return;

    WaitForMultipleObjects(g_subCount, g_subProcs, TRUE, INFINITE);
     g_subCount  = 0
}
```
 
  to decrease count would not work? (I never programmed with c++ and dll) can you explain why

**Comment by nomi-san** [comment]
yeah, it should work fine if you call MP_WaitAll() to ensure all processes are exited.

**Comment by Devil4ngle** [comment]
Thanks I did as I said and compiled and it works like charm.
